### ISSUE TITLE
export 'ParseError' (imported as 'ParseError') was not found in 'katex' (possible exports: default)

### ISSUE THREAD

**Issue by iamgabrielsoft** [benrbray/prosemirror-math#59]
After downloading the package I get this in return 

Am currently using Prosemirror library, I wonder why am getting this error in return 

Framework: Reactjs
Language: Typescript 

How do I resolve this issue?

**Comment by CraigMcCahill** [comment]
Exactly the same problem here, 


```
[ERROR] No matching export in "node_modules/katex/dist/katex.mjs" for import "ParseError"

    node_modules/@benrbray/prosemirror-math/dist/index.es.js:6:16:
      6 │ import katex, { ParseError } from 'katex';
        ╵                 ~~~~~~~~~~
```


 package versions:

```
"@benrbray/prosemirror-math": "^0.2.2",
"katex": "^0.15.1",
"react": "^17.0.2",

```

Also tried with version `0.16.8` of Katex from here https://www.npmjs.com/package/katex

Thanks Craig

**Comment by benrbray** [comment]
I resolved this when updating dependencies in a recent PR, the fix will appear in the next release
