### ISSUE TITLE
Safari - regular expression

### ISSUE THREAD

**Issue by amilich** [benrbray/prosemirror-math#6]
Looks like safari doesn't support lookbehind yet - any alternate regex for the `math_inline` input rule?

**Comment by benrbray** [comment]
There's actually a [simpler regex commented out in the code](https://github.com/benrbray/prosemirror-math/blob/master/src/plugins/math-inputrules.ts#L46) that avoids using lookbehinds, but you will lose the ability to escape `$` symbols with `\$`.

* Original `/(?<!\\)\$(.+)(?<!\\)\$/`
* Simplified `/\$(.+)\$/`

In the future, I'll probably look for a more cross-browser-friendly way to escape.

**Comment by amilich** [comment]
Thank you! I've actually been testing with `/[^\\]?\$([^$\n\\]+)[^\\][\$]/`, which seems to work okay, and then adding 1 to `start` inside `replaceRangeWith` if the match starts with a space. Probably could be cleaner.
